version: '2'
services:

  hello_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      hello_example:
        aliases:
          - hello_server
    volumes:
      - ./jaeger-config.json:/etc/jaeger-config.json

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      hello_example:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

networks:
  hello_example: {}
